### ISSUE TITLE
Bytte tema?

### ISSUE THREAD

**Issue by sondr3** [lesesalen/gummiand.no#7]
Synes det funker fint akkurat nå men på sikt når dokumentet vokser er jeg redd for at det blir litt uoversiktlig. Jeg satt opp en kjapp `mkdocs`-side for echo karriere ([docs.echokarriere.no](docs.echokarriere.no)) med et Material design som jeg synes funker veldig fint, men det ser kanskje litt vel "dokumentasjon" ut. Synes [Just The Docs](https://pmarsceill.github.io/just-the-docs/) er et veldig clean og oversiktlig tema. Tanker @mtverraen @mrboen94?

**Comment by mtverraen** [comment]
Støtter å bytte til "Just The Docs", men da må vel Jekyl brukes istedenfor å bare publishe markdown dokumentet med gh-pages?

**Comment by sondr3** [comment]
`gh-pages` bruker allerede Jekyll, https://pmarsceill.github.io/just-the-docs/#quick-start-use-as-a-github-pages-remote-theme :shipit:

**Comment by mtverraen** [comment]
I så fall tenker jeg det bare er å bytte!
